### ISSUE TITLE
gitlab不能显示tree？？？

### ISSUE THREAD

**Issue by sky508** [ineo6/git-master#52]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26371416/102900102-d0023e80-44a6-11eb-9ac4-ec910c2eb39b.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - Platform(GitHub, GitLab, Gitee, Gitea):
 - Browser and Version: 
 - GitMaster Version:

**Additional context**

**Comment by ineo6** [comment]
请按照issue格式填写内容，你这样我无法知道到底有什么问题。





------------------ 原始邮件 ------------------
发件人: sky508 <notifications@github.com&gt;
发送时间: 2020年12月22日 22:42
收件人: ineo6/git-master <git-master@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ineo6/git-master] gitlab不能显示tree？？？ (#52)





 
Describe the bug
 A clear and concise description of what the bug is.
 
 
To Reproduce
 Steps to reproduce the behavior:
 
Expected behavior
 A clear and concise description of what you expected to happen.
 
Screenshots
 If applicable, add screenshots to help explain your problem.
 
Context (please complete the following information):
  
Platform(GitHub, GitLab, Gitee, Gitea): 

Browser and Version: 

GitMaster Version: 
 
Additional context
 Add any other context about the problem here.

**Comment by ineo6** [comment]
默认`gitlab.com`域名会自动开启，其他域名需要点击地址栏右侧的扩展图标开启配置。

**Comment by dian-yu-luo** [comment]
> 默认`gitlab.com`域名会自动开启，其他域名需要点击地址栏右侧的扩展图标开启配置。

我的在GitHub中也不能打开tree，我不明白是我的配置问题吗，描述很困难，像是这样：
先点击这个位置
![ET}%9S5S ~AL%URG_TU WQ8](https://user-images.githubusercontent.com/58965094/103152418-b3c21280-47c2-11eb-8493-f1aaf03a6ad2.png)
chu出现这个结果
![8C~I~B_R38TPD8F1ZQP) LT](https://user-images.githubusercontent.com/58965094/103152432-e5d37480-47c2-11eb-96c6-6271e1b0cf1b.png)
